language: node_js
node_js:
- 6
branches:
  only:
  - master
before_script:
- npm install
script: ls -al README.md
after_success: npm run deploy
env:
  global:
    - QIITA_POST_ID: 8fff46c201bf9eaeba4a
    - QIITA_POST_TITLE: "フロントエンドチェックリスト（日本語訳）"
    - secure: BT8j/bT0mWtdp9GE0y8ey9DsChCX14iL5Lw3/O7SCtyJdcAF2kXCANUV9Uav/KD7VMa57RfKKpzoOm/l1Zbzt3Q2dniFHGICCSTDcnsBuXBKjvpVKimP+kIxtCmH7qN58er4PV09PZFupQy7X0dd6FvKK09kBwfBCBw1fUfmTtCUfh541024mVw+0uaqTst/7b/OlsI3jnNrVo6ixjN5jVpaHwpP3pLm1OQNaK92NmBFdmtIxq1i/sNuoSyvHs30GrCaqHF/2d95EZiN7+EKO+6yxaLbRNVXOhqO2ksK0yeXS/auXhw3eJ3VqcUQivs6UA+s6+GzUbKvR9VLokfPV5hm5yNcpuoCnRaMy0vnJ44hA68QQ/Yt8NXHMD8PS0S9FEnuX++yBYMM55bVB63iwGiPvFIpzaOGu5/DlceQGA3chw2v+Z9G3bPAM/XC3cJIzwbY5KOpqdXigbaNvbWCW+EElsqSCEGZFo5+VfTllUZ+gGc52crKk7HFJ/XBw6Rmuaub8U2PiqnddopjWUJA9MWnAE9i8LPnBa4ZJqyBTDdhl+QbtnvMD4BNnScuwKp8j85g+Wu3A7jNHQQ5Qld+rCoDnHe3H6VczY5lwuan8Em0LwI9eeOP5S8RA0b5nK4I3/Fmq3RAm+vdF/vRphzjauXUi/B+0irpbTnjSfEPWpU=
